### ISSUE TITLE
Uncaught Exception: Page 'index.md' was not found

### ISSUE THREAD

**Issue by gentao123** [devaneando/Wikitten#110]
After deploy new version,can not access wikitten normally
evn:
nginx/1.12.1
PHP 7.3.4
page error:
Fatal error: Uncaught Exception: Page 'index.md' was not found in /www/mywiki/wiki.php:52 Stack trace: #0 /www/mywiki/wiki.php(133): Wiki->{closure}() #1 /www/mywiki/wiki.php(401): Wiki->_render('index.md') #2 /www/mywiki/wiki.php(339): Wiki->indexAction() #3 /www/mywiki/index.php(34): Wiki->dispatch() #4 {main} thrown in /www/mywiki/wiki.php on line 52
someone met this problem?

**Comment by coffe1nk2** [comment]
I got this error too

> [Fri Apr 17 00:38:10.523325 2020] [php7:error] [pid 3181] [client 192.168.50.1:48293] PHP Fatal error:  Uncaught Exception: Page 'index.md' was not found in /var/www/html/wikitten/wiki.php:52\nStack trace:\n#0 /var/www/html/wikitten/wiki.php(133): Wiki->{closure}()\n#1 /var/www/html/wikitten/wiki.php(401): Wiki->_render('index.md')\n#2 /var/www/html/wikitten/wiki.php(339): Wiki->indexAction()\n#3 /var/www/html/wikitten/index.php(34): Wiki->dispatch()\n#4 {main}\n  thrown in /var/www/html/wikitten/wiki.php on line 52

Apache/2.4.6 (CentOS)
PHP 7.3.4

**Comment by fjxhkj** [comment]
`vim config.php`
uncomment the `define('ENABLE_EDITING', true);` line.
try again!

**Comment by bulubula** [comment]
如果define('LIBRARY' 定义的目录和 index.php 不在同级目录，那么'ENABLE_EDITING' = false 就会导致报这个错误，只有像楼上说的 ‘ENABLE_EDITING'=true才能正常运行，我不会英语 T_T

**Comment by bulubula** [comment]
vi wiki.php
comment the line 52,
like    // throw new Exception("Page '$page' was not found");
try again!
